baseurl = "https:PaolaDaft.github.io/UnLibroParaTodos"
title = "METAP"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
# disqusShortname = "YOUR_DISQUS_SHORTNAME"
# Enable Google Analytics by entering your tracking code
#googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "Un libro para todos: educación inclusiva"
  copyright = "&copy;2022 METAP"
  sidebarAbout = ['"Un libro para todos" es una iniciativa de METAP donde el objetivo es crear y distribuir libros de educación inclusiva ya que creemos que la mejor forma de promover la inclusión es forma conciencia de como hacer compañía es esta comunidades que son una minoría']
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "you@yoursite.com"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  facebook      = "full page or profile url in facebook"
  email         = "andrepaolagd@gmail.com.com"
  twitter       = "https://twitter.com/Paola_Daft"
  linkedin      = "https://www.linkedin.com/in/andrea-paola-garc%C3%ADa-659292124/"
  instagram     = "https://www.instagram.com/paola_daft/"
  youtube       = "full profile url in youtube"
  whatsapp      = "wa.me service link"
